import './globals.css'
import { Roboto } from 'next/font/google'
import NavBar from './components/navBar'

const roboto = Roboto({ subsets: ['latin'], weight: '400'})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className} style={{height:'100vh'}}>
        <NavBar/>
        {children}
      </body>
    </html>
  )
}
